name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Commit mesajinda "-live-" varsa calisir
    if: contains(github.event.head_commit.message, '-live-')

    steps:
      - name: Sunucuya Baglan ve Guncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # 1. Proje Klasorune Git
            cd /home/who-dat-idols

            # 2. GitHub'dan En Guncel Kodlari Cek (Zorla)
            git fetch --all
            git reset --hard origin/main
            
            # 3. Gradle'a Calisma Izni Ver (Kritik Adim!)
            chmod +x gradlew

            # 4. Temiz Derleme Yap (Release Modu Hazirligi)
            ./gradlew clean build -x test --no-daemon

            # 5. Servisi Yeniden Baslat (Prod Modunda Kalkacak)
            systemctl restart whodatidols
            
            # 6. Durum Raporu Ver
            systemctl status whodatidols --no-pager