name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # --- KRITIK NOKTA ---
    # Bu satir, commit mesajinin icinde "-live-" kelimesini arar.
    # Eger yoksa, bu islem (job) tamamen atlanir ve sunucuya dokunulmaz.
    if: contains(github.event.head_commit.message, '-live-')
    # --------------------

    steps:
      - name: Sunucuya Baglan ve Guncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/who-dat-idols
            git pull origin main
            ./gradlew clean build -x test --no-daemon
            systemctl restart whodatidols
            systemctl status whodatidols --no-pager